[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

lib_deps = 
    ESP32Servo
    adafruit/Adafruit BNO08x @ ^1.2.5
    TinyGPSPlus
    jgromes/RadioLib @ ^6.6.0